### ISSUE TITLE
Draft MOU for co-working spaces

### ISSUE THREAD

**Issue by dlindahl** [techramento/techramento.github.io#8]
This would be a standard MOU we can come to the table with. Generally speaking, the exact details would be open to negotiation.

**Comment by roughani** [comment]
Things to include:
- One day per week reserved for Techramento
- Expectations (noise levels, projector, scheduling conflicts, etc.)
  - Meetup with 30 days notice that date isn't available
  - Allow for set-up and tear down time when scheduling
    - On-site point of contact should be communicated to Meetup
  - Accomodating meetups in open areas by proactively providing opportunities for noninterference so that neither the meetup nor the co-working space members interupt each other
    - This may be accomplished by providing a designated conference room isolated from the open space to accomodate co-working space members
  - Audio/Visual equipment should be appropriate to the size of the event
  - An accessible and clean restroom 
  - The user group's Code of Conduct shall apply to the coworking space during the time of the meetup event
- Marketing and promotion benefits

**Comment by roughani** [comment]
Super rough and incomplete [scaffolding in the wiki](https://github.com/techramento/techramento.github.io/wiki/Draft-Co-working-Space-MOU).

**Comment by dlindahl** [comment]
Tabled to next meeting (in order to be tabled to the next meeting :smile:)

**Comment by roughani** [comment]
We discussed that MOU will last for 6 months.

**Comment by dlindahl** [comment]
Tabled to next meeting while @roughani formalizes this document.

**Comment by dlindahl** [comment]
@roughani will have informal talks with some co-working spaces over the next month to get feedback on our plan and MOU. This will take place before any formal meeting and MOU signing takes places.

**Comment by dlindahl** [comment]
On hold until #33 is complete.

**Comment by dlindahl** [comment]
We've decided to table this as its a little too ambitious to start off with. Keeping this as an ambition for the future makes more sense at the moment.
